2019-03-08 11:27:45,419 INFO: Starting Updater
2019-03-08 11:27:45,521 ERROR: Failed to connect org HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /orgs/moodysanalytics (Caused by SSLError(SSLError("bad handshake: SysCallError(10054, 'WSAECONNRESET')")))
2019-03-08 11:28:49,814 INFO: Starting Updater
2019-03-08 11:28:50,057 INFO: Organization(login="moodysanalytics")
